on: push
name: Build ChopChop
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Unit Tests
      run: go test ./...
    - name: Install gox
      run: go get github.com/mitchellh/gox
      if: startsWith(github.ref, 'refs/tags/')
    - name: Build using gox
      run: gox -ldflags "-X main.Version=$BUILD_VERSION -X main.BuildDate=$BUILD_DATE" -output "dist/ChopChop_{{.OS}}_{{.Arch}}"
      if: startsWith(github.ref, 'refs/tags/')
    - name: Upload ChopChop builds
      uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: chopchop-artifacts
        path: dist/*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*